### ISSUE TITLE
NHANES has duplicate rows

### ISSUE THREAD

**Issue by homerhanumat** [rpruim/NHANES#1]
Is it intended (perhaps for some pedagogical purpose) that `NHANES` has duplicates rows? for example:

```
NHANES[NHANES$ID == 51624]
```

**Comment by rpruim** [comment]
The NHANES package contains two data sets.  The `NHANES` data set was produced from the raw data set at the University of Auckland using (I believe) a fairly simple weighted resampling method, so it is possible for rows to be duplicated.  This allows for upweighting of undersampled subpopulations. 

As the warning and disclaimer in the help indicate, this is better than using the raw data without considering weights, but it should not be considered a method for serious research.

## NHANES warning
The following warning comes directly from the NHANES web site:

For NHANES datasets, the use of sampling weights and sample design variables is recommended for all analyses because the sample design is a clustered design and incorporates differential probabilities of selection. If you fail to account for the sampling parameters, you may obtain biased estimates and overstate significance levels.

## Disclamer
Please note that the data sets provided in this package are derived from the NHANES database and have been adapted for educational purposes. As such, they are NOT suitable for use as a research database. For research purposes you should download original data files from the NHANES website and follow the analysis instructions given there.

**Comment by homerhanumat** [comment]
My bad.  I missed this in your Help:  "NHANES contains 10,000 rows of data resampled from NHANESraw to undo these oversampling effects. "

Thanks!
